---
# tasks file for roles/database
# Launhch postgres database
- name: Launch database
  docker_container:
    name: "{{ database_container_name }}"
    image: eliottc13/tp1_db
    networks:
      - name: my-network
    volumes: /my/own/datadir:/var/lib/postgresql/data
    env:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
    pull: true
