name: deploy
on:
  #to begin you want to launch this job in main and develop
  workflow_run:
    workflows: [publish_push_images_docker]
    types:
      - completed
    branches:
      - main
jobs:
  deploy: 
    #deploy ansible playbook
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #install ansible
      - name: Install Ansible
        run: sudo apt-get install ansible

      - name: Setting up Vault password
        run: |
          echo "${{ secrets.VAULT_PASSWORD }}" > ~/vault_pass.pem
          chmod 600 ~/vault_pass.pem
      
    #run ansible playbook
      - name: Run Ansible playbook
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H eliott.caumon.takima.cloud >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ansible-playbook -i ./DevOps/TP1_DevOps/TP3/ansible/inventories/setup.yml ./DevOps/TP1_DevOps/TP3/ansible/playbook.yml --vault-password-file=~/vault_pass.pem
